### ISSUE TITLE
Output port

### ISSUE THREAD

**Issue by Nolazz** [Zillode/OSCeleton-KinectSDK2#1]
Hello ! How would it be possible to change the number of the outport (7110) ?
It would be great if this option could appear in the main window of OSCeleton2 !
Thank you for interest,
Regards

**Comment by Zillode** [comment]
Start with `oscPort 7111` on the [commandline](https://github.com/Zillode/OSCeleton-KinectSDK2/blob/710be2541858b16e6f5d8ac6dd438db39fdab23b/OSCeleton.cs#L58) or update the default value in the [code](https://github.com/Zillode/OSCeleton-KinectSDK2/blob/710be2541858b16e6f5d8ac6dd438db39fdab23b/OSCeleton.cs#L29).

**Comment by Nolazz** [comment]
Thank you !

**Comment by Nolazz** [comment]
Hello,
I'm really sorry, I'm not good at coding but I really need to use OSCeleton for a project at school.
I need to change the OSC port but I can't manage to do it.
When you say "Start with oscPort 7111 on the commandline" that means in the Microsoft invit cmd, that's it ? With a new OSC port as argument ? Could you show me an example of the syntaxe please cause I can't manage to do it ?
And I tried to modify the number of the port in the code (in Visual Studio 2015) and I tried to generate a new build, but I've an error about zillode.be.pfx file 
"Unable to get MD5 checksum for the key file "publish\zillode.be.pfx". Could not find file 'C:\Users\dexte\Desktop\OSCeleton-KinectSDK2-master\publish\zillode.be.pfx'
Could you help me please ?

**Comment by Zillode** [comment]
Remove the reference to `zillode.be.pfx` in Project->Properties->Signing>disable

**Comment by Nolazz** [comment]
Thank you, now I can generate the build, but when I try to run it (OSCeleton-KinectSDK2.exe), it crashes with this error message : "The identity of the application is not defined"

**Comment by Zillode** [comment]
Disable `CheckForShortcut` https://github.com/Zillode/OSCeleton-KinectSDK2/blob/710be2541858b16e6f5d8ac6dd438db39fdab23b/OSCeleton.cs#L44

**Comment by Nolazz** [comment]
When you say "disable" does it mean removing the line ?

**Comment by Zillode** [comment]
Yes

**Comment by Nolazz** [comment]
Great, that works !
Just one error again when i generate the build : 
" warning CS3001: the type of argument 'UdpWriter' is not CLS conform"
Maybe it's not so important ?

**Comment by Zillode** [comment]
No it's a warning. Please carefully read what the system is telling you, it'll help you in the future to resolve many other issues.

**Comment by Nolazz** [comment]
Thank you for your precious help and time.
Now i'm going to try to use OSCeleton 2 with Kinectar, but I have a lot of adaptations to do yet (for example change the string by removing "/OSCeleton2" before "/joint" in the OSC messages... And changing the scale. 
By the way, have you just applied a scaling by 1000 on the coordonates values between OSCeleton and OSCeleton 2 ? Or is it more complexe ?
