### ISSUE TITLE
zillode.be.pfx issue

### ISSUE THREAD

**Issue by Nolazz** [Zillode/OSCeleton-KinectSDK2#2]
Hello,
Sorry, I've another problem : when i try to generate the solution with Microsoft Visual Studio 2015, I've have this error message :
" Unable to get MD5 checksum for the key file "publish\zillode.be.pfx". Could not find file 'C:\Users\dexte\Desktop\OSCeleton-KinectSDK2-master\publish\zillode.be.pfx "
I'm on W10.
Any idea ?
Thanks for your help.

**Comment by micuat** [comment]
for those who had this issue, the solution is explained in another thread: https://github.com/Zillode/OSCeleton-KinectSDK2/issues/1#issuecomment-283143627
